[project]
name = "horario-ponto"
version = "0.1.0"
description = "Script para encontrar o horário em que eu bati ponto no estágio no dia de hoje. Baseado em web-scraping"
authors = [
    {name = "Sevenings",email = "lvlassis.2@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests (>=2.31,<3.0.0)",
    "beautifulsoup4 (>=4.12,<5.0.0)"
]

[project.scripts]
horario_ponto = "horario_ponto:main"


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
