[flavor]
use = "everforest-medium"






[icon]
prepend_dirs = [
	{ name = "Documentos", text = "" },
	{ name = "Imagens", text = "" },
	{ name = "Musicas", text = "" },
	{ name = "Playground", text = "󱊈" },
	{ name = "Projetos", text = "" },
]

